### ISSUE TITLE
get an erro when i try your repo

### ISSUE THREAD

**Issue by bakiwebdev** [fardjad/node-llmatic#1]
Hello & nice work 

i got this error when i try your repo on my local machine, any help would be much help, thanks

![image](https://github.com/fardjad/node-llmatic/assets/57604289/a37bfcb2-0cd6-463e-908b-80157f3d2a25)

**Comment by fardjad** [comment]
I think you're running it on Windows which is not supported at the moment. My suggestion for now is to run it on [WSL](https://learn.microsoft.com/en-us/windows/wsl/install)

**Comment by bakiwebdev** [comment]
it works perfectly with ubuntu, but for some reason couldn't get a response when i use this model url https://huggingface.co/mosaicml/mpt-7b

could you please suggest where i can get the model path, and how to download the model and then how to give a name for the model name,

```
lmatic config
? What do you want to do? Download a model
? Enter the model URL:
https://huggingface.co/mosaicml/mpt-7b
? Enter the file name (will skip download if file
exists): mot-7b.bin
? What do you want to do? Generate a config file
? Select a model: mot-7b.bin


📝 Generated config file: llmatic.config.json


? What do you want to do? (Use arrow keys)
❯ Download a model
  Generate a config file
 ──────────────
  Exit ```

**Comment by bakiwebdev** [comment]
Wow, that's really helpful! Thank you for your assistance. I've decided to close this issue, but before doing so, I would like to mention a couple of additional things.

Firstly, I noticed that whenever I run the model, my CPU usage spikes up to 100%. This behavior doesn't occur when I run the model using Python or the GPT4ALL.exe program. It's peculiar and raises concerns about the computational demands of the model. I would appreciate any suggestions or insights on how to optimize the CPU usage while running the model.

Secondly, I noticed a discrepancy in the Swagger documentation for my API. The documentation starts with a "/" route, but in reality, the API works correctly when accessed via the "/v1/..." prefix. This inconsistency might confuse users who are referring to the Swagger documentation. It would be great if we could update the documentation to accurately reflect the correct starting route ("/v1/") for accessing the API endpoints.

Once again, thank you for your hard work and assistance. I'm grateful for your support in resolving these issues.

**Comment by fardjad** [comment]
No problem at all! Thanks for your feedback. I actually noticed the issue with the API base URL yesterday and fixed it.
I also updated the docs and created a short video tutorial to explain how it works. You might want to try the latest version as well.

As for the CPU usage, my suggestion is to decrease the number of threads in the generated config file.
