### ISSUE TITLE
Want to contribute to the repo

### ISSUE THREAD

**Issue by arre-ankit** [fardjad/node-llmatic#200]
I am also building a ChatLLM as project and faced same issue of that the OpenAI api are costly and trying to figure out a way to add Open Source LLM as API but didn't find for TypeScript and came across your project.
I would love to contribute to the this project.

**Comment by fardjad** [comment]
That sounds great! You might want to have a look at this issue to get started:

https://github.com/fardjad/node-llmatic/issues/132

**Comment by arre-ankit** [comment]
Sure I will check it out.
